
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Faraz
 */
public class InvoiceForm extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceForm
     */
    public InvoiceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        Id = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        Cnic = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Departure = new javax.swing.JLabel();
        PickDate = new javax.swing.JLabel();
        Nodays = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Car = new javax.swing.JLabel();
        CarType = new javax.swing.JLabel();
        label13 = new java.awt.Label();
        address = new javax.swing.JLabel();
        label14 = new java.awt.Label();
        typeCar = new javax.swing.JLabel();
        label15 = new java.awt.Label();
        car = new javax.swing.JLabel();
        label16 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label4 = new java.awt.Label();
        Fina = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        lnam = new javax.swing.JLabel();
        cnic = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        gender = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        departure = new javax.swing.JLabel();
        pickdate = new javax.swing.JLabel();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        nodays = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        city = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        label12 = new java.awt.Label();
        q = new javax.swing.JLabel();
        ID2 = new javax.swing.JLabel();
        la = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 119, 25));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Start-Menu-Search-icon.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        Total.setEditable(false);
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 90, -1));
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 104, -1, -1));
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 134, -1, -1));
        getContentPane().add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 195, -1, -1));
        getContentPane().add(Cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 215, -1, -1));
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 244, -1, -1));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 282, -1, -1));
        getContentPane().add(Departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 336, -1, -1));
        getContentPane().add(PickDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 387, -1, -1));
        getContentPane().add(Nodays, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 443, -1, -1));
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 489, -1, -1));
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 544, -1, -1));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 597, -1, -1));
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 104, -1, -1));
        getContentPane().add(Car, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 167, -1, -1));
        getContentPane().add(CarType, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 137, -1, -1));

        label13.setBackground(new java.awt.Color(0, 0, 0));
        label13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Address");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("First Name");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        label14.setBackground(new java.awt.Color(0, 0, 0));
        label14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label14.setForeground(new java.awt.Color(255, 255, 255));
        label14.setText("Type Of Car");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        typeCar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typeCar.setForeground(new java.awt.Color(255, 255, 255));
        typeCar.setText("First Name");
        getContentPane().add(typeCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        label15.setBackground(new java.awt.Color(0, 0, 0));
        label15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label15.setForeground(new java.awt.Color(255, 255, 255));
        label15.setText("Car");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        car.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        car.setForeground(new java.awt.Color(255, 255, 255));
        car.setText("First Name");
        getContentPane().add(car, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        label16.setBackground(new java.awt.Color(0, 0, 0));
        label16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setText("Total");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add-User-icon.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 80, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Main");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 80, -1));

        label4.setBackground(new java.awt.Color(0, 0, 0));
        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("ID");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        Fina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fina.setForeground(new java.awt.Color(255, 255, 255));
        Fina.setText("First Name");
        getContentPane().add(Fina, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("First Name");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        label2.setBackground(new java.awt.Color(0, 0, 0));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("LastName");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lnam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lnam.setForeground(new java.awt.Color(255, 255, 255));
        lnam.setText("First Name");
        getContentPane().add(lnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        cnic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cnic.setForeground(new java.awt.Color(255, 255, 255));
        cnic.setText("First Name");
        getContentPane().add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        label3.setBackground(new java.awt.Color(0, 0, 0));
        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Cnic");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        label5.setBackground(new java.awt.Color(0, 0, 0));
        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Gender");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("First Name");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("First Name");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        label6.setBackground(new java.awt.Color(0, 0, 0));
        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Date");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        label7.setBackground(new java.awt.Color(0, 0, 0));
        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("DepartureTime");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        departure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        departure.setForeground(new java.awt.Color(255, 255, 255));
        departure.setText("First Name");
        getContentPane().add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        pickdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pickdate.setForeground(new java.awt.Color(255, 255, 255));
        pickdate.setText("First Name");
        getContentPane().add(pickdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        label8.setBackground(new java.awt.Color(0, 0, 0));
        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("Pick Up Date");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        label9.setBackground(new java.awt.Color(0, 0, 0));
        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("No of Days");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        nodays.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nodays.setForeground(new java.awt.Color(255, 255, 255));
        nodays.setText("First Name");
        getContentPane().add(nodays, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("First Name");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        label10.setBackground(new java.awt.Color(0, 0, 0));
        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Contact");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        label11.setBackground(new java.awt.Color(0, 0, 0));
        label11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("City");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        city.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        city.setForeground(new java.awt.Color(255, 255, 255));
        city.setText("First Name");
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("First Name");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        label12.setBackground(new java.awt.Color(0, 0, 0));
        label12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label12.setForeground(new java.awt.Color(255, 255, 255));
        label12.setText("Email");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        q.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        q.setForeground(new java.awt.Color(255, 255, 255));
        q.setText("INVOICE");
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 470, -1));

        ID2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID2.setForeground(new java.awt.Color(255, 255, 255));
        ID2.setText("First Name");
        getContentPane().add(ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        la.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        la.setIcon(new javax.swing.ImageIcon(getClass().getResource("/63035193-dark-blue-wallpapers.jpg"))); // NOI18N
        getContentPane().add(la, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 650, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if (jTextField1.getText()==""){
            JOptionPane.showMessageDialog(null, "Invalid ID");
            }
            
        Invoice frm=new Invoice(la, Fina, lnam, cnic, address, contact, gender, date, pickdate, departure, nodays, city, email,  typeCar, car);
       if (frm.searchBooking(jTextField1.getText())==true){
        frm.setBill(jTextField1.getText());
        RentCar rent =new RentCar();
        double w=Double.parseDouble(nodays.getText());
          
        
     if (typeCar.getText().equals("Go")){
           String e=Double.toString(rent.Go_car(w));
        
        Total.setText(e);}
        else if (typeCar.getText().equals("Economic")){
            String r=Double.toString(rent.X_car(w));
            Total.setText(r);
                }}
       else
       {
           JOptionPane.showMessageDialog(null, "Invalid ID","Error",JOptionPane.OK_OPTION);
       }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Invalid ID","Error",JOptionPane.OK_OPTION);
        }
     
       
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Bookings book = new Bookings(pickdate.getText(), date.getText(), departure.getText(), nodays.getText(),car.getText(), Fina.getText(), lnam.getText(), cnic.getText(), gender.getText(), contact.getText(), address.getText(), email.getText(), date.getText(), city.getText(), "", typeCar.getText());
        Invoice in = new Invoice(book, Total.getText());
        in.add();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Main main=new Main();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Car;
    private javax.swing.JLabel CarType;
    private javax.swing.JLabel City;
    private javax.swing.JLabel Cnic;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Departure;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fina;
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel ID2;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Nodays;
    private javax.swing.JLabel PickDate;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel address;
    private javax.swing.JLabel car;
    private javax.swing.JLabel city;
    private javax.swing.JLabel cnic;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel date;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel la;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JLabel lnam;
    private javax.swing.JLabel nodays;
    private javax.swing.JLabel pickdate;
    private javax.swing.JLabel q;
    private javax.swing.JLabel typeCar;
    // End of variables declaration//GEN-END:variables
}
